### ISSUE TITLE
Consider "OrganismDispersal" as a name?

### ISSUE THREAD

**Issue by Datseris** [rafaqz/Dispersal.jl#11]
Hey there,

Dispersal.jl sounds like a cool name, but depending on your background it may mean totally different things. E.g. I come from electron transport and there dispersal really has no connection to what it represents here.

If you want to consider a title more relevant to what the package does, it might help you gain more visibility for this work, which seems to be very good work by looking at the plots. "OrganismDispersal" is something I just thought on the fly, but you are more qualified to choose :P

**Comment by rafaqz** [comment]
Maybe! Although dispersal has a pretty clear meaning in ecology (the major use case) and it's a nice short name. It also doesn't have to be organisms... Half these rules could work in other contexts. Like the spread of viruses ;)
