### ISSUE TITLE
Drop `Exact` from growth model names

### ISSUE THREAD

**Issue by rafaqz** [rafaqz/Dispersal.jl#51]
These are legacy from when there where two methods for each. Now it seems pretty verbose.

I think `LogisticGrowth` is better than `ExactLogisticGrowth`, as for `ExactExponentialGrowth` and especially `ExactExponentialGrowthMap` is really getting too long. @jamesmaino any thoughts? I think you named these.

**Comment by jamesmaino** [comment]
Yeah, fine to change. It was previous to separate the inexact method using Euler's method.
