### ISSUE TITLE
precalc_auxtimeindex of GeoArray

### ISSUE THREAD

**Issue by virgile-baudrot** [rafaqz/Dispersal.jl#73]
I feel like I could solve this one, but I failed...

```julia
 no method matching precalc_auxtimeindex(::GeoArray...
```

```julia
Closest candidates are:
  precalc_auxtimeindex(::AbstractArray{var"#s18",3} where var"#s18", ::Rule, ::DynamicGrids.SimData) at C:\Users\virgi\.julia\packages\Dispersal\592tM\src\utils.jl:18
  precalc_auxtimeindex(::AbstractArray{var"#s16",3} where var"#s16", ::Rule, ::DynamicGrids.SimData, ::Any) at C:\Users\virgi\.julia\packages\Dispersal\592tM\src\utils.jl:18    
  precalc_auxtimeindex(::AbstractArray{T,2} where T, 
```

Well, I did simulation by recovering reshaping Arrays includes in `GeoArray.data`... but i'm sure you have it

**Comment by rafaqz** [comment]
What are you trying to do exactly? 

`precalc_auxtimeindex` is going away soon, this is all done automatically by DynamicGrids now. You just pass in the `GeoArray`/`DimArray` and it finds the righ timet index to match the current frame of the simulation - you can just index like its 2d with `get(data, Aux(:somekey), I)`.

Hope to get it merged and pushed some time soon.

**Comment by virgile-baudrot** [comment]
It was when using a `rule`. I have to clean and update all that.
